/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSpinRouteImport } from './routes/_authenticated/spin'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlayRouteImport } from './routes/_authenticated/play'
import { Route as AuthenticatedPacksRouteImport } from './routes/_authenticated/packs'
import { Route as AuthenticatedMyAssetsRouteImport } from './routes/_authenticated/my-assets'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSpinRouteImport } from './routes/_authenticated/admin/spin'
import { Route as AuthenticatedAdminPacksRouteImport } from './routes/_authenticated/admin/packs'
import { Route as AuthenticatedAdminMultipliersRouteImport } from './routes/_authenticated/admin/multipliers'
import { Route as AuthenticatedAdminEconomyRouteImport } from './routes/_authenticated/admin/economy'
import { Route as AuthenticatedAdminCollectionsRouteImport } from './routes/_authenticated/admin/collections'
import { Route as AuthenticatedAdminAssetsRouteImport } from './routes/_authenticated/admin/assets'
import { Route as AuthenticatedAdminModulesSlugRouteImport } from './routes/_authenticated/admin/modules.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSpinRoute = AuthenticatedSpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlayRoute = AuthenticatedPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPacksRoute = AuthenticatedPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyAssetsRoute = AuthenticatedMyAssetsRouteImport.update({
  id: '/my-assets',
  path: '/my-assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSpinRoute = AuthenticatedAdminSpinRouteImport.update({
  id: '/spin',
  path: '/spin',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPacksRoute = AuthenticatedAdminPacksRouteImport.update({
  id: '/packs',
  path: '/packs',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMultipliersRoute =
  AuthenticatedAdminMultipliersRouteImport.update({
    id: '/multipliers',
    path: '/multipliers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEconomyRoute =
  AuthenticatedAdminEconomyRouteImport.update({
    id: '/economy',
    path: '/economy',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCollectionsRoute =
  AuthenticatedAdminCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAssetsRoute =
  AuthenticatedAdminAssetsRouteImport.update({
    id: '/assets',
    path: '/assets',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModulesSlugRoute =
  AuthenticatedAdminModulesSlugRouteImport.update({
    id: '/modules/$slug',
    path: '/modules/$slug',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/collections': typeof AuthenticatedCollectionsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/my-assets': typeof AuthenticatedMyAssetsRoute
  '/packs': typeof AuthenticatedPacksRoute
  '/play': typeof AuthenticatedPlayRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/spin': typeof AuthenticatedSpinRoute
  '/admin/assets': typeof AuthenticatedAdminAssetsRoute
  '/admin/collections': typeof AuthenticatedAdminCollectionsRoute
  '/admin/economy': typeof AuthenticatedAdminEconomyRoute
  '/admin/multipliers': typeof AuthenticatedAdminMultipliersRoute
  '/admin/packs': typeof AuthenticatedAdminPacksRoute
  '/admin/spin': typeof AuthenticatedAdminSpinRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/modules/$slug': typeof AuthenticatedAdminModulesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/home': typeof AuthenticatedHomeRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/my-assets': typeof AuthenticatedMyAssetsRoute
  '/packs': typeof AuthenticatedPacksRoute
  '/play': typeof AuthenticatedPlayRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/spin': typeof AuthenticatedSpinRoute
  '/admin/assets': typeof AuthenticatedAdminAssetsRoute
  '/admin/collections': typeof AuthenticatedAdminCollectionsRoute
  '/admin/economy': typeof AuthenticatedAdminEconomyRoute
  '/admin/multipliers': typeof AuthenticatedAdminMultipliersRoute
  '/admin/packs': typeof AuthenticatedAdminPacksRoute
  '/admin/spin': typeof AuthenticatedAdminSpinRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/modules/$slug': typeof AuthenticatedAdminModulesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/my-assets': typeof AuthenticatedMyAssetsRoute
  '/_authenticated/packs': typeof AuthenticatedPacksRoute
  '/_authenticated/play': typeof AuthenticatedPlayRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/spin': typeof AuthenticatedSpinRoute
  '/_authenticated/admin/assets': typeof AuthenticatedAdminAssetsRoute
  '/_authenticated/admin/collections': typeof AuthenticatedAdminCollectionsRoute
  '/_authenticated/admin/economy': typeof AuthenticatedAdminEconomyRoute
  '/_authenticated/admin/multipliers': typeof AuthenticatedAdminMultipliersRoute
  '/_authenticated/admin/packs': typeof AuthenticatedAdminPacksRoute
  '/_authenticated/admin/spin': typeof AuthenticatedAdminSpinRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/modules/$slug': typeof AuthenticatedAdminModulesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/collections'
    | '/home'
    | '/inventory'
    | '/my-assets'
    | '/packs'
    | '/play'
    | '/profile'
    | '/spin'
    | '/admin/assets'
    | '/admin/collections'
    | '/admin/economy'
    | '/admin/multipliers'
    | '/admin/packs'
    | '/admin/spin'
    | '/admin/users'
    | '/admin/'
    | '/admin/modules/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/collections'
    | '/home'
    | '/inventory'
    | '/my-assets'
    | '/packs'
    | '/play'
    | '/profile'
    | '/spin'
    | '/admin/assets'
    | '/admin/collections'
    | '/admin/economy'
    | '/admin/multipliers'
    | '/admin/packs'
    | '/admin/spin'
    | '/admin/users'
    | '/admin'
    | '/admin/modules/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/collections'
    | '/_authenticated/home'
    | '/_authenticated/inventory'
    | '/_authenticated/my-assets'
    | '/_authenticated/packs'
    | '/_authenticated/play'
    | '/_authenticated/profile'
    | '/_authenticated/spin'
    | '/_authenticated/admin/assets'
    | '/_authenticated/admin/collections'
    | '/_authenticated/admin/economy'
    | '/_authenticated/admin/multipliers'
    | '/_authenticated/admin/packs'
    | '/_authenticated/admin/spin'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/modules/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/spin': {
      id: '/_authenticated/spin'
      path: '/spin'
      fullPath: '/spin'
      preLoaderRoute: typeof AuthenticatedSpinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play': {
      id: '/_authenticated/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof AuthenticatedPlayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packs': {
      id: '/_authenticated/packs'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof AuthenticatedPacksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-assets': {
      id: '/_authenticated/my-assets'
      path: '/my-assets'
      fullPath: '/my-assets'
      preLoaderRoute: typeof AuthenticatedMyAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/spin': {
      id: '/_authenticated/admin/spin'
      path: '/spin'
      fullPath: '/admin/spin'
      preLoaderRoute: typeof AuthenticatedAdminSpinRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/packs': {
      id: '/_authenticated/admin/packs'
      path: '/packs'
      fullPath: '/admin/packs'
      preLoaderRoute: typeof AuthenticatedAdminPacksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/multipliers': {
      id: '/_authenticated/admin/multipliers'
      path: '/multipliers'
      fullPath: '/admin/multipliers'
      preLoaderRoute: typeof AuthenticatedAdminMultipliersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/economy': {
      id: '/_authenticated/admin/economy'
      path: '/economy'
      fullPath: '/admin/economy'
      preLoaderRoute: typeof AuthenticatedAdminEconomyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/collections': {
      id: '/_authenticated/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AuthenticatedAdminCollectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/assets': {
      id: '/_authenticated/admin/assets'
      path: '/assets'
      fullPath: '/admin/assets'
      preLoaderRoute: typeof AuthenticatedAdminAssetsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/modules/$slug': {
      id: '/_authenticated/admin/modules/$slug'
      path: '/modules/$slug'
      fullPath: '/admin/modules/$slug'
      preLoaderRoute: typeof AuthenticatedAdminModulesSlugRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAssetsRoute: typeof AuthenticatedAdminAssetsRoute
  AuthenticatedAdminCollectionsRoute: typeof AuthenticatedAdminCollectionsRoute
  AuthenticatedAdminEconomyRoute: typeof AuthenticatedAdminEconomyRoute
  AuthenticatedAdminMultipliersRoute: typeof AuthenticatedAdminMultipliersRoute
  AuthenticatedAdminPacksRoute: typeof AuthenticatedAdminPacksRoute
  AuthenticatedAdminSpinRoute: typeof AuthenticatedAdminSpinRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminModulesSlugRoute: typeof AuthenticatedAdminModulesSlugRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAssetsRoute: AuthenticatedAdminAssetsRoute,
    AuthenticatedAdminCollectionsRoute: AuthenticatedAdminCollectionsRoute,
    AuthenticatedAdminEconomyRoute: AuthenticatedAdminEconomyRoute,
    AuthenticatedAdminMultipliersRoute: AuthenticatedAdminMultipliersRoute,
    AuthenticatedAdminPacksRoute: AuthenticatedAdminPacksRoute,
    AuthenticatedAdminSpinRoute: AuthenticatedAdminSpinRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminModulesSlugRoute: AuthenticatedAdminModulesSlugRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMyAssetsRoute: typeof AuthenticatedMyAssetsRoute
  AuthenticatedPacksRoute: typeof AuthenticatedPacksRoute
  AuthenticatedPlayRoute: typeof AuthenticatedPlayRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSpinRoute: typeof AuthenticatedSpinRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMyAssetsRoute: AuthenticatedMyAssetsRoute,
  AuthenticatedPacksRoute: AuthenticatedPacksRoute,
  AuthenticatedPlayRoute: AuthenticatedPlayRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSpinRoute: AuthenticatedSpinRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
